// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteScene(arg1) {
  return window['go']['main']['App']['DeleteScene'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportSessionCSV(arg1) {
  return window['go']['main']['App']['ExportSessionCSV'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentHeartRate() {
  return window['go']['main']['App']['GetCurrentHeartRate']();
}

export function GetCurrentStyle() {
  return window['go']['main']['App']['GetCurrentStyle']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetI18nMessages() {
  return window['go']['main']['App']['GetI18nMessages']();
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSessionStats() {
  return window['go']['main']['App']['GetSessionStats']();
}

export function GetStyles() {
  return window['go']['main']['App']['GetStyles']();
}

export function KillOverlay() {
  return window['go']['main']['App']['KillOverlay']();
}

export function LaunchOverlay() {
  return window['go']['main']['App']['LaunchOverlay']();
}

export function ResetSession() {
  return window['go']['main']['App']['ResetSession']();
}

export function SaveScene(arg1) {
  return window['go']['main']['App']['SaveScene'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartScan() {
  return window['go']['main']['App']['StartScan']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function SwitchScene(arg1) {
  return window['go']['main']['App']['SwitchScene'](arg1);
}

export function SwitchStyle(arg1) {
  return window['go']['main']['App']['SwitchStyle'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
