// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {ble} from '../models';
import {stats} from '../models';
import {style} from '../models';

export function CheckForUpdate():Promise<Record<string, any>>;

export function Connect(arg1:string):Promise<void>;

export function DeleteScene(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportSessionCSV(arg1:string):Promise<string>;

export function GetConfig():Promise<config.GlobalConfig>;

export function GetConnectionStatus():Promise<string>;

export function GetCurrentHeartRate():Promise<number>;

export function GetCurrentStyle():Promise<string>;

export function GetDevices():Promise<Array<ble.DeviceInfo>>;

export function GetI18nMessages():Promise<Record<string, string>>;

export function GetScenes():Promise<Array<config.Scene>>;

export function GetSessionHistory():Promise<Array<stats.SessionSummary>>;

export function GetSessionStats():Promise<Record<string, any>>;

export function GetStyles():Promise<Array<style.Definition>>;

export function KillOverlay():Promise<void>;

export function LaunchOverlay():Promise<void>;

export function ResetSession():Promise<void>;

export function SaveScene(arg1:config.Scene):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function StartScan():Promise<void>;

export function StopScan():Promise<void>;

export function SwitchScene(arg1:string):Promise<void>;

export function SwitchStyle(arg1:string):Promise<void>;

export function UpdateConfig(arg1:config.GlobalConfig):Promise<void>;
